name: Update JS dependencies

on:
  workflow_dispatch:
  push:
    branches:
      - 'renovate/**'

jobs:
  update:
    name: Install and update JS dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install --no-package-lock
      - name: Commit and push changes
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Update js dependencies" || exit 0
          git push
